#!/bin/bash

echo "🎯 NammaGear - Manual Setup Steps"
echo "==================================
"
echo "Since automated setup requires admin access, please follow these manual steps:"
echo ""
echo "OPTION 1: Install PostgreSQL via Homebrew (Recommended)"
echo "--------------------------------------------------------"
echo "1. Install Homebrew (if not installed):"
echo "   /bin/bash -c \"\$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\""
echo ""
echo "2. Install PostgreSQL:"
echo "   brew install postgresql@16"
echo "   brew services start postgresql@16"
echo ""
echo "3. Create database:"
echo "   createdb nammagear"
echo ""
echo "4. Run setup:"
echo "   cd apps/api"
echo "   npx prisma generate"
echo "   npx prisma db push"
echo "   npx prisma db seed"
echo "   cd ../.."
echo ""
echo "5. Start the app:"
echo "   pnpm dev"
echo ""
echo ""
echo "OPTION 2: Use Supabase (Cloud Database - No installation needed!)"
echo "-------------------------------------------------------------------"
echo "1. Go to: https://supabase.com/dashboard/sign-in"
echo "2. Sign up/Login (free)"
echo "3. Create a new project"
echo "4. Copy the 'Connection string' (Session mode)"
echo "5. Update apps/api/.env:"
echo "   DATABASE_URL=\"your-connection-string-here\""
echo ""
echo "6. Run setup:"
echo "   cd apps/api"
echo "   npx prisma generate"
echo "   npx prisma db push"
echo "   npx prisma db seed"
echo "   cd ../.."
echo ""
echo "7. Start the app:"
echo "   pnpm dev"
echo ""
echo ""
echo "✨ After setup, your app will be available at:"
echo "   Frontend: http://localhost:3000"
echo "   Backend API: http://localhost:3001"
echo ""
