#!/usr/bin/env bash
# VPS Deploy Checklist — run each step manually after VPS is provisioned

set -euo pipefail

echo "=== Hostinger VPS Deployment Checklist ==="
echo ""
echo "✅ DONE: Local Docker stack working (http://localhost:3000)"
echo "✅ DONE: Deployment files committed (b90b3b9)"
echo ""
echo "📋 NEXT STEPS (run these commands):"
echo ""
echo "1️⃣ Push to GitHub (needs your auth):"
echo "   cd ~/Desktop/student-gear-shop"
echo "   git push origin dev"
echo ""
echo "2️⃣ Order VPS in hPanel:"
echo "   • Open: https://hpanel.hostinger.com/"
echo "   • VPS → Order new VPS"
echo "   • Pick: Mumbai 2 (DC ID 23) or Mumbai (DC ID 13)"
echo "   • Plan: KVM 2 (2GB RAM, 2 vCPU) minimum"
echo "   • OS: Ubuntu 22.04"
echo ""
echo "3️⃣ After VPS provisioned, get details:"
echo "   hapi vps vm list"
echo "   # Note the VM ID from output"
echo ""
echo "4️⃣ Set root password:"
echo "   hapi vps vm set-root-password --vm-id <YOUR_VM_ID> --password <strong-password>"
echo ""
echo "5️⃣ Get VPS IP:"
echo "   hapi vps vm get --vm-id <YOUR_VM_ID> --format json | jq -r .ip_address"
echo "   # Or just: hapi vps vm get --vm-id <YOUR_VM_ID>"
echo ""
echo "6️⃣ SSH to VPS and run bootstrap:"
echo "   ssh root@<VPS_IP>"
echo "   # On the VPS:"
echo "   curl -fsSL https://raw.githubusercontent.com/vishvmkr-cmd/nammagear/dev/deploy/vps-install.sh | bash"
echo ""
echo "7️⃣ Configure secrets (still on VPS):"
echo "   cd /opt/app/deploy"
echo "   nano .env"
echo "   # Set:"
echo "   #   JWT_SECRET=<random-32+-char-string>"
echo "   #   CLOUDINARY_CLOUD_NAME=<your-cloudinary-name>"
echo "   #   CLOUDINARY_API_KEY=<key>"
echo "   #   CLOUDINARY_API_SECRET=<secret>"
echo "   #   CORS_ORIGIN=https://microlynk.shop,https://www.microlynk.shop"
echo "   #   COOKIE_DOMAIN=.microlynk.shop"
echo ""
echo "8️⃣ Configure Caddy (still on VPS):"
echo "   sudo nano /etc/caddy/Caddyfile"
echo "   # Replace contents with:"
echo "   # microlynk.shop, www.microlynk.shop {"
echo "   #     reverse_proxy localhost:3000"
echo "   #     encode gzip"
echo "   # }"
echo "   sudo systemctl restart caddy"
echo ""
echo "9️⃣ Start Docker stack (still on VPS):"
echo "   cd /opt/app"
echo "   docker compose -f deploy/docker-compose.yml up -d"
echo "   docker compose -f deploy/docker-compose.yml logs -f"
echo ""
echo "🔟 Configure DNS in hPanel:"
echo "   • hPanel → Domains → microlynk.shop → Manage → DNS"
echo "   • Set A records:"
echo "   #   Type  Name  Value        TTL"
echo "   #   A     @     <VPS_IP>     3600"
echo "   #   A     www   <VPS_IP>     3600"
echo "   • Wait ~5 minutes for propagation"
echo ""
echo "1️⃣1️⃣ Verify deployment:"
echo "   curl -I https://microlynk.shop"
echo "   # Should return 200 with valid TLS cert"
echo ""
echo "📚 Full docs: deploy/README.md"
echo "📋 CLI setup: .cursor/hostinger-setup.md"
